// Typefolio scaffold — zero-dependency CLI that writes a fresh site.config.ts.
// Run: npm run scaffold
import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const isTTY = Boolean(input.isTTY);

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const CONFIG_PATH = join(root, 'site.config.ts');

const PRESETS = [
  { id: 'paper', label: 'Paper — warm light theme (default)' },
  { id: 'ink', label: 'Ink — inverted dark theme' },
  { id: 'forest', label: 'Forest — deep green + bone' },
  { id: 'clay', label: 'Clay — warm paper + terracotta' },
];

const rl = isTTY ? createInterface({ input, output }) : null;

/**
 * Read one answer. In a real terminal this is interactive; when stdin is
 * piped (or not a TTY), answers are consumed line-by-line from the pipe so
 * `printf '...\n' | npm run scaffold` also works.
 */
let pipedLines = [];
let pipedIndex = 0;
if (!isTTY) {
  try {
    pipedLines = readFileSync(0, 'utf8').split(/\r?\n/);
  } catch {
    pipedLines = [];
  }
}

async function ask(question, def = '') {
  const prompt = `${question}${def ? ` [${def}]` : ''}: `;
  if (!isTTY) {
    const answer = (pipedLines[pipedIndex++] ?? '').trim();
    output.write(`${prompt}${answer}\n`);
    return answer || def;
  }
  const answer = (await rl.question(prompt)).trim();
  return answer || def;
}

/** Make free text safe to embed in a TS template literal. */
function clean(value) {
  return value.replace(/\\/g, '\\\\').replace(/`/g, "'").replace(/\$\{/g, '{');
}

function toStringArray(value) {
  return value
    .split(',')
    .map((part) => clean(part.trim()))
    .filter(Boolean);
}

function renderConfig(a) {
  const roles = a.roles.map((r) => `      '${r}',`).join('\n');
  const heroLines = a.heroLines.map((l) => `      '${l}',`).join('\n');
  const identityLines = a.identityLines.map((l) => `      '${l}',`).join('\n');
  const manifestoLines = a.manifestoLines.map((l) => `      '${l}',`).join('\n');

  return `import type { SiteConfig } from './src/lib/config-schema';

/**
 * Generated by \`npm run scaffold\`. Edit freely — this file is validated
 * with zod at build time, so mistakes fail loudly instead of shipping.
 */
export const siteConfig: SiteConfig = {
  meta: {
    title: '${a.name} — ${a.roles[0] ?? 'Designer'}',
    description: 'Portfolio of ${a.name}.',
    url: 'https://example.com',
  },

  tokens: {
    preset: '${a.preset}',
  },

  profile: {
    name: '${a.name}',
    roles: [
${roles}
    ],
    location: '${a.location}',
    availability: '${a.availability}',
  },

  hero: {
    eyebrow: '${a.eyebrow}',
    lines: [
${heroLines}
    ],
  },

  identity: {
    lines: [
${identityLines}
    ],
  },

  intro: '${a.intro}',

  manifesto: {
    lines: [
${manifestoLines}
    ],
    mark: "© '26",
  },

  work: {
    heading: 'Selected Work',
    range: '24–26',
    items: [
      {
        title: 'Project One',
        image: '/assets/works/work-01.svg',
        href: '#',
        tags: ['Design'],
      },
      {
        title: 'Project Two',
        image: '/assets/works/work-02.svg',
        href: '#',
        tags: ['Build'],
      },
      {
        title: 'Project Three',
        image: '/assets/works/work-03.svg',
        href: '#',
        tags: ['Design', 'Build'],
      },
    ],
  },

  awards: {
    heading: 'Awards & Recognition',
    groups: [
      {
        year: "'26",
        items: [
          {
            name: 'Site of the Day',
            org: 'Independent Design Awards',
            certificate: '/assets/awards/award-01.svg',
          },
        ],
      },
    ],
  },

  contact: {
    heading: "Let's work together.",
    email: '${a.email}',
    socials: [{ label: 'Website', href: 'https://example.com' }],
  },

  motion: {
    enabled: true,
    reveal: 'stacked-line',
    marqueeSpeed: 32,
    ease: 'power3.out',
  },
};

export default siteConfig;
`;
}

async function main() {
  console.log('\n  Typefolio scaffold — answer a few prompts, get a fresh site.config.ts.\n');

  if (existsSync(CONFIG_PATH)) {
    const overwrite = (await ask('site.config.ts already exists. Overwrite?', 'y')).toLowerCase();
    if (overwrite !== 'y' && overwrite !== 'yes') {
      console.log('Aborted — existing site.config.ts kept.');
      if (rl) rl.close();
      return;
    }
  }

  const name = clean(await ask('Your name', 'Alex Carter'));
  const roles = toStringArray(
    await ask('Roles (comma-separated)', 'Product Designer, Creative Developer'),
  );
  const location = clean(await ask('Location', 'Portland, Oregon'));
  const availability = clean(await ask('Availability note', 'Available for new projects'));
  const email = clean(await ask('Contact email', 'hello@example.com'));
  const eyebrow = clean(await ask('Hero eyebrow', 'Independent designer & developer'));
  const heroLines = toStringArray(
    await ask('Hero headline lines (comma-separated)', 'Design, & Code'),
  );
  const identityLines = toStringArray(
    await ask('Identity stack lines (comma-separated)', `${name}, Designs, Interfaces, & Systems`),
  );
  const intro = clean(
    await ask(
      'Intro sentence',
      'I design and build websites, products, and interfaces — pairing strong typography with thoughtful engineering.',
    ),
  );
  const manifestoLines = toStringArray(
    await ask('Manifesto lines (comma-separated)', 'Good work, speaks quietly.'),
  );

  console.log('\nToken presets:');
  PRESETS.forEach((p, i) => console.log(`  ${i + 1}. ${p.label}`));
  const choice = await ask('Pick a preset (1-4)', '1');
  const preset = PRESETS[Number.parseInt(choice, 10) - 1] ?? PRESETS[0];

  const answers = {
    name,
    roles: roles.length > 0 ? roles : ['Designer'],
    location,
    availability,
    email,
    eyebrow,
    heroLines: heroLines.length > 0 ? heroLines : ['Hello'],
    identityLines: identityLines.length > 0 ? identityLines : [name],
    intro,
    manifestoLines: manifestoLines.length > 0 ? manifestoLines : ['Make good work.'],
    preset: preset.id,
  };

  writeFileSync(CONFIG_PATH, renderConfig(answers));
  if (rl) rl.close();

  console.log(`\n  Wrote site.config.ts with the "${preset.id}" preset.`);
  console.log(
    '  Next: npm run dev — then replace the placeholder work images in public/assets/.\n',
  );
}

main().catch((error) => {
  console.error(error);
  if (rl) rl.close();
  process.exit(1);
});
